spring:
  application:
    name: config-client

  profiles:
    active: kafka_to_elastic

  cloud:
    config:
      username: admin
      password: "{cipher}920d17bb6955246f94607ccb67d2a39b0088b853d109bf9198b8dec2ee48f450"

  config:
    import: "configserver:http://localhost:8888"