server:
  port: 8888

spring:
  application:
    name: configserver

  cloud:
    config:
      server:
        git:
          uri: https://github.com/merve-naz/spring-cloud-config-server-repository.git
          default-label: main
          username: merve-naz
          password: ENC(SIFRELENMIS_TOKEN)
          clone-on-start: true

    fail-fast: true

logging:
  level:
    ROOT: DEBUG